import { StyleSheet } from "react-native";

export const getStylesBadge = (colorBadge:string, colors:any, isBigNumber:boolean|undefined|0, value:number|undefined|0) => StyleSheet.create({
    container: {
      position: 'relative',
    },
    badge: {
      width: 8,
      height: 8,
      top: -2,
      right: -6,
      backgroundColor: colorBadge,
      borderColor:colors.borderLight,
      borderWidth:1,
      borderRadius: 50,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.5,
      shadowRadius: 1.5,
      elevation: 2,
    },
    badgeNumber: {
      width: 18,
      height: 18,
      top: -8,
      right: -9,
      backgroundColor: colors.badge,
      borderRadius: 50,
      borderColor:colors.borderLight,
      borderWidth:1,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.5,
      shadowRadius: 1.5,
      elevation: 2,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: colors.textPrimaryInverse,
      fontSize: 12,
      fontWeight: '500',
    },
    badgeWithChildren: {
      width: isBigNumber ? 24 : !value ? 8 : 18,
      height: !value ? 8 : 18,
      backgroundColor: colors.badge,
      borderRadius: 50,
      borderColor:colors.borderLight,
      borderWidth:1,
      alignItems: 'center',
      justifyContent: 'center',
      color: colors.textPrimaryInverse,
      zIndex: 1,
      elevation: 1,
    },
    badgeBigNumber: {
      width: 24,
      borderRadius: 50,
      borderColor:colors.borderLight,
      borderWidth:1,
      backgroundColor: colors.badge,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.5,
      shadowRadius: 1.5,
      elevation: 2,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      top: -8,
      right: -14,
      height: 18,
      fontSize: 12,
      fontWeight: '500',
    },
  });