export type { Skin, KnownSkinName, SkinName } from './types'
export { MOVISTAR_SKIN } from './constants'
export { getSkinByName } from './utils'
export { getMovistarSkin } from './movistar'
export { palette as movistarPalette } from './movistar'